---
# Passwords
bootstrap__active_users_passwords:            '{{ bootstrap__active_users | get_user_passwords }}'
bootstrap__admin_pass:                        '{{lookup("vault", "users",             field="admin",              env="all", stage="all")}}'
bootstrap__root_pass:                         '{{lookup("vault", "users",             field="root",               env="all", stage="all")}}'
# Consul
bootstrap__consul_encryption_key:             '{{lookup("vault", "consul/config",     field="encryption-key",       env="all", stage="all")}}'
bootstrap__consul_agent_acl_token:            '{{lookup("vault", "consul/acl-tokens", field="agent-default",        env="all", stage="all")}}'
bootstrap__consul_service_registration_token: '{{lookup("vault", "consul/acl-tokens", field="service-registration", env="all", stage="all")}}'
bootstrap__consul_agent_admin_token:          '{{lookup("vault", "consul/acl-tokens", field="agent-admin",          env="all", stage="all")}}'
bootstrap__consul_certs_ca_crt:               '{{lookup("vault", "consul/certs",      field="ca.pem",               env="all", stage="all")}}'
bootstrap__consul_certs_client_crt:           '{{lookup("vault", "consul/certs",      field="client.pem",           env="all", stage="all")}}'
bootstrap__consul_certs_client_key:           '{{lookup("vault", "consul/certs",      field="client-key.pem",       env="all", stage="all")}}'
# Vault certificate
bootstrap__vault_ca_cert:                     '{{ lookup("passwordstore", "services/vault/certs/root-ca/cert returnall=true")}}'
bootstrap__vault_client_cert:                 '{{ lookup("passwordstore", "services/vault/certs/client-host/cert returnall=true")}}'
bootstrap__vault_client_key:                  '{{ lookup("passwordstore", "services/vault/certs/client-host/privkey returnall=true")}}'
# SSHGuard
bootstrap__sshguard_whitelist_extra:           ['{{lookup("vault", "sshguard/whitelist",    field="jakubgs-home", env="all", stage="all")}}']
# Wireguard
wireguard_consul_acl_token:                   '{{lookup("vault", "consul/acl-tokens", field="wireguard",          env="all", stage="all")}}'
# Wazuh Agent
wazuh_agent_enrollment_key:                   '{{ lookup("vault", "manager/config", field="enrollment-password",  env="hq",  stage="wazuh")}}'
wazuh_root_ca:                                '{{ lookup("vault", "root-ca",        field="certificate",          env="hq",  stage="wazuh")}}'

# Volume of Trace level logs is too high and fills up ES cluster.
bootstrap__rsyslog_filter_rules: ['TRC']

# Docker registry
bootstrap__docker_registries:
  - url:      'https://harbor.status.im'
    username: 'robot$wakuorg+infra-waku'
    password: '{{ lookup("vault", "robot", field="robot$wakuorg+infra-waku", env="ci", stage="harbor")}}'

# Custom SSH accounts for Nimbus fleet, should start from UID 8000.
bootstrap__active_extra_users:
  - { name: hanno,  uid: 8003, admin: true, key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDlvmNGKxoddAmOuXvjm0II0M82aLjczb8F1ZTSV7zyvKaw6DNuaN6c6ZCdUvdjfF4hdEwMXNB37Cr5oysPo41rIuii+RVPd+c2WLZnC/MCg8d6b0/mREIfpuEMlz+u4lyr8/DST7zO4Ke95w5kVGtlh2kR88F9mlJlkyq2NCiqBU/blKObOjqS8OMRuMJ0GpwzF9+/dfXVahzdgHgKS0Q1ATvLHL0DvZSAGwHfHcIV5nF0ddRCofX4L2shIImZk5dAsATQTkT2gNWObhF6KuWbVyuhsLfRletzdnf8jUYm9Uatf7Woa9CxbPjdGxVxniZblmOumcaCNgaioKs0qeZzwNQmgJ/PXXw9uVWhDUYvNh7Cz+SNTVm4WG1tEk3WO9EU5dcCTgfEa94LUl5G+yXYX8H00spubpiWXv/0RjEQX4CZeu0pff209GLDWdpIaV8p9QVFBr8X8t8jw5zw5j/PxkprcT5P2A1t+WOUn9LrBzOJ1iAU3oJV3ZMYQhUS78= hanno@status.im', pass: '$6$8A5HRyRqnKrFh1uy$s6RfYze6cQQ.BKKDaKm358y.KHZ14bTTwPx0bbVC6pJBsp3WQ.DYU90FFY5wMGmbjU4bxrBmdHw66ovR2OdEu0' }
  - { name: ivan,   uid: 8004, admin: true, key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJBdm8y1PfWjT1pioaWJSZ2ETrUySb+dS/ifDg+VIpLY ivansete@status.im', pass: '$y$j9T$6d3ZQNLzh7Yb/787cDugT1$NxgTUW46/uCGyT/h3mOayfhYAxdb77Or./RV0o4d6h8' }
  - { name: zoltan, uid: 8005, admin: true, key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFNYe8dLIGTTrTYgKfaXhai6uQmJfewJPi3MXwIeM2Zk zoltan@status.im', pass: '$y$j9T$mDPUq.x9/dZqypIV9.VZa/$w/MxJ/Qlsq9kZwjJCdA/9dhN0go/58rmD1cM07IQsc2' }
  - { name: gabriel,uid: 8006, admin: true, key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2/Z8eRjB+uYwC8OTYwMI5HYaZvpD68fKLvo2f6/2abzs5MTskXVlDFB7XDsFw+s1oloKKKNl+VYA7WR4qO8c0usMHll2Io1XuRdMJQsUaERpxKOeddIpsOaAmHea7Dh/JVdC07aQm0QDYnfSXD66k//LD2EfjSp/9L6ObPbtWSYnMtlIxmNq8hdP33R59HAcpZtXnubElQhxAMtY4pnBNI/jJS44uan2asNT4vftUMUAmSGjwTVgbRHiE1nyvwcisvy8kDQILXxchetRcWZw/aztmvWUYOTebgdvlMirZRLw6gLjjKMoGgRIpI/vDHZyYezEdzjOLf//4qcD4ez5H gabriel@status.im' }
