---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Configure Waku Storage DB Nodes
  hosts: node-db
  pre_tasks:
    - name: Enable Maintenance Mode
      command: 'maintenance Ansible run by {{ ansible_env.USER }}'
      tags: always
  post_tasks:
    - name: Disable Maintenance Mode
      command: 'maintenance disable'
      tags: always
  roles:
    - { role: infra-role-open-ports,  tags: open-ports  }
    - { role: infra-role-swap-file,   tags: swap-file   }
    - { role: infra-role-postgres-ha, tags: postgres-ha }

- name: Configure Waku Nodes
  hosts: node
  pre_tasks:
    - name: Enable Maintenance Mode
      command: 'maintenance Ansible run by {{ ansible_env.USER }}'
      tags: always
  post_tasks:
    - name: Disable Maintenance Mode
      command: 'maintenance disable'
      tags: always
  roles:
    - { role: infra-role-open-ports,  tags: open-ports  }
    - { role: infra-role-swap-file,   tags: swap-file   }
    - { role: infra-role-certbot,     tags: certbot     }
    - { role: infra-role-nim-waku,    tags: nim-waku    }
    - { role: infra-role-nginx,       tags: nginx       }
